---
- block:
  - name: Install Graylog (Ubuntu/Debian)
    apt:
      name: "{{ graylog_package_name }}"
      state: present
      update_cache: yes
      
  - name: Ensure Graylog is enabled (Ubuntu/Debian)
    systemd:
      name: "{{ graylog_package_name }}"
      state: started
      enabled: yes
  when: ansible_os_family == 'Debian'

- block:
  - name: Import Graylog GPG key
    command: rpm --import /etc/pki/rpm-gpg/{{ graylog_gpg_key }}
    when: graylog_offline_install

  - name: Install Graylog (CentOS/RHEL)
    yum:
      name: "{{ graylog_package_name }}"
      state: present

  - name: Install Graylog dependencies (CentOS/RHEL)
    yum:
      name: "{{ item }}"
      state: present
    with_items: 
      - "{{ graylog_rpm_dependencies }}"

  - name: 'Populate service facts'
    service_facts:

  - name: Allow Graylog http ports (CentOS/RHEL)
    firewalld:
      port: "{{ graylog_rh_http_port }}/tcp"
      permanent: yes
      immediate: yes
      state: enabled
    when: ansible_facts.services['firewalld.service']['status'] == 'enabled' 

  - name: Allow the web server to access the network (CentOS/RHEL)
    seboolean:
      name: "{{ item }}"
      state: yes
      persistent: yes
    with_items:
      - httpd_can_network_connect
      - httpd_can_network_connect_db
    when: ansible_selinux == 'enabled'

  when: ansible_os_family == 'RedHat'

- block:
  - name: "Generate systemd file"
    template:
      src: graylog.service.j2
      dest: /usr/lib/systemd/system/graylog-server.service
    notify: Restart Graylog

  - name: Ensure service is enabled
    service:
      name: "{{ graylog_service_name }}"
      enabled: yes
      state: started

  - name: Ensure directory exist
    file:
      path: "{{ item }}"
      state: directory
      owner: graylog 
      group: graylog
    with_items:
      - "{{ graylog_config_path }}"
      - "{{ graylog_data_path }}"
      - "{{ graylog_default_dir }}"

  - name: Copy graylog files to new path
    copy:
      src: /usr/share/graylog-server/
      dest: "{{ graylog_default_dir }}"
      owner: graylog
      group: graylog
      remote_src: yes
  when: graylog_change_install_path